
##Ver todo lo de la Base de datos
GET http://localhost:8080/estudiantes/


##Para ver por id
GET http://localhost:8080/estudiantes/4


##Para crear sin id (Id es autoincrementable)
POST http://localhost:8080/estudiantes
Content-Type: application/json

{
    "nombre": "Tata",
    "apellido": "Cordoba",
    "edad": 61
}


##Para eliminar
DELETE  http://localhost:8080/estudiantes/7


##para actualizar
PUT http://localhost:8080/estudiantes/2
Content-Type: application/json

{ 
    "nombre": "Alan",
    "apellido": "Jesus",
    "edad": 22
}
